// Field Manual: catálogo editorial dos oito módulos. Este arquivo mantém a documentação separada da lógica operacional.
export type GuideField = { label: string; meaning: string };

export type ModuleGuide = {
  key: string;
  title: string;
  mission: string;
  scope: string;
  family: string;
  fields: GuideField[];
  recommendedFlow: string[];
  whyDifferent: string;
  limitations: string;
};

export const MODULE_GUIDES: Record<string, ModuleGuide> = {
  aliexpress: {
    key: 'aliexpress', title: 'AliExpress Master', family: 'Hardware e sessão',
    mission: 'Gerar um perfil técnico para o fluxo do módulo AliExpress e explicar quais sinais de dispositivo são preparados.',
    scope: 'Este menu prioriza dados técnicos; não é um gerador de identidade civil completa.',
    fields: [
      { label: 'MAC', meaning: 'Identificador de rede exibido no perfil técnico.' },
      { label: 'IMEI', meaning: 'Identificador de hardware móvel gerado para o perfil.' },
      { label: 'Fingerprint', meaning: 'Assinatura técnica usada para agrupar sinais do navegador e do dispositivo.' },
      { label: 'Resolução', meaning: 'Dimensão de tela associada ao perfil escolhido.' },
    ],
    recommendedFlow: ['Leia o escopo do módulo.', 'Gere um perfil novo.', 'Revise os campos técnicos.', 'Use o fluxo de abertura disponível no menu.'],
    whyDifferent: 'CPF, endereço e outros dados de persona não aparecem porque este módulo foi desenhado como perfil técnico, não como cadastro pessoal.',
    limitations: 'A tela documenta o que o código prepara; ela não garante que um serviço externo aceitará ou manterá esses valores.',
  },
  facebook: {
    key: 'facebook', title: 'Facebook Device Manager', family: 'Hardware e sessão',
    mission: 'Organizar a geração do perfil técnico usado pelo fluxo do Facebook, com leitura clara dos sinais mostrados.',
    scope: 'O módulo é centrado em hardware e navegador. Dados pessoais não fazem parte do cartão técnico padrão.',
    fields: [
      { label: 'Dispositivo', meaning: 'Modelo e fabricante escolhidos para compor o perfil.' },
      { label: 'MAC', meaning: 'Identificador de rede apresentado no perfil.' },
      { label: 'IMEI', meaning: 'Identificador móvel associado ao dispositivo gerado.' },
      { label: 'User-Agent', meaning: 'Texto que descreve navegador, sistema e modelo para o contexto da sessão.' },
    ],
    recommendedFlow: ['Confira a finalidade do módulo.', 'Gere o dispositivo.', 'Leia os identificadores exibidos.', 'Siga o botão de abertura/injeção apenas quando entender o fluxo.'],
    whyDifferent: 'Nome, telefone, CPF e endereço não são exibidos porque o schema atual é device-only.',
    limitations: 'A presença de um campo na interface não comprova aceitação por plataformas de terceiros.',
  },
  instagram: {
    key: 'instagram', title: 'Instagram Device Manager', family: 'Hardware e sessão',
    mission: 'Gerar e apresentar os sinais técnicos usados pelo fluxo do Instagram.',
    scope: 'Este menu mostra hardware, fingerprint e navegador; ele não representa uma ficha cadastral completa.',
    fields: [
      { label: 'Dispositivo', meaning: 'Modelo, fabricante e versão de sistema do perfil.' },
      { label: 'MAC', meaning: 'Identificador de rede exibido para conferência.' },
      { label: 'IMEI', meaning: 'Identificador móvel do perfil gerado.' },
      { label: 'User-Agent', meaning: 'Identidade textual do navegador e sistema informada ao contexto local.' },
    ],
    recommendedFlow: ['Leia o escopo.', 'Gere o dispositivo.', 'Confirme o modelo e os identificadores.', 'Use a ação de abertura disponível.'],
    whyDifferent: 'Dados civis e de recuperação não aparecem porque o módulo não usa o gerador de persona completa.',
    limitations: 'O guia explica o comportamento local da aplicação e não promete resultado em um site externo.',
  },
  email: {
    key: 'email', title: 'Email Master', family: 'Credenciais de email',
    mission: 'Gerar endereços e credenciais de email com opções de provedor, país e formato.',
    scope: 'Este é um gerenciador de email e histórico local; não é um emulador de hardware móvel.',
    fields: [
      { label: 'Provedor', meaning: 'Define o serviço/domínio base usado no endereço.' },
      { label: 'País', meaning: 'Ajuda a escolher o padrão regional do endereço.' },
      { label: 'Tipo de email', meaning: 'Controla a composição do nome e dos números.' },
      { label: 'Contas salvas', meaning: 'Lista os registros que foram mantidos no armazenamento local.' },
    ],
    recommendedFlow: ['Escolha o provedor.', 'Selecione país e formato.', 'Gere o email.', 'Copie ou salve a credencial conforme o fluxo do menu.'],
    whyDifferent: 'MAC, IMEI, resolução e fingerprint não são exibidos porque o objetivo é credencial, não dispositivo.',
    limitations: 'O armazenamento local depende do navegador atual e não substitui uma conta real do provedor.',
  },
  manus: {
    key: 'manus', title: 'Manus AI Master', family: 'Hardware + persona',
    mission: 'Combinar um perfil de dispositivo com dados de persona usados pelo fluxo do Manus.',
    scope: 'Este módulo é mais amplo: pode mostrar hardware, identidade e contexto de conta no mesmo perfil.',
    fields: [
      { label: 'Hardware', meaning: 'Modelo, MAC, IMEI, resolução e fingerprint do dispositivo.' },
      { label: 'Persona', meaning: 'Nome, email, telefone, data e outros campos pessoais do perfil.' },
      { label: 'Status', meaning: 'Indica o estado local do fluxo de preparação ou abertura.' },
      { label: 'Convite', meaning: 'Campo opcional para o link informado pelo usuário.' },
    ],
    recommendedFlow: ['Leia o resumo do perfil.', 'Gere o dispositivo e a persona.', 'Revise campos técnicos e pessoais.', 'Use o fluxo do menu mantendo os dados documentados.'],
    whyDifferent: 'Este menu mostra mais dados porque seu schema combina device profile e personal profile.',
    limitations: 'Dados pessoais devem ser tratados com responsabilidade; a interface não valida identidade real nem garante aceitação externa.',
  },
  tiktok: {
    key: 'tiktok', title: 'TikTok Device Master', family: 'Hardware + persona',
    mission: 'Gerar um perfil técnico e um conjunto de dados pessoais compatível com o fluxo do TikTok.',
    scope: 'O módulo combina sinais de dispositivo com uma persona parcial, por isso sua tela é mais rica que os módulos device-only.',
    fields: [
      { label: 'Modelo', meaning: 'Dispositivo e fabricante selecionados no gerador específico do TikTok.' },
      { label: 'IMEI/MAC', meaning: 'Identificadores técnicos mostrados para inspeção do perfil.' },
      { label: 'Persona', meaning: 'Dados pessoais associados ao perfil, quando o gerador fornece esses campos.' },
      { label: 'Fingerprint', meaning: 'Assinatura técnica do perfil de navegador/dispositivo.' },
    ],
    recommendedFlow: ['Leia o escopo.', 'Gere o perfil.', 'Revise hardware e persona.', 'Siga o fluxo operacional do menu apenas após a conferência.'],
    whyDifferent: 'O TikTok usa um gerador específico, com conjunto próprio de campos; por isso ele não é idêntico ao Facebook ou ao Gmail.',
    limitations: 'A implementação local não controla políticas, verificações ou decisões de uma plataforma externa.',
  },
  claude: {
    key: 'claude', title: 'Claude AI Master', family: 'Sessão e contexto',
    mission: 'Organizar uma sessão de uso com credenciais e contexto técnico necessários ao fluxo do módulo Claude.',
    scope: 'O foco está em sessão, rede e contexto de navegação, não em um inventário completo de hardware.',
    fields: [
      { label: 'Email', meaning: 'Identifica a conta informada para a sessão.' },
      { label: 'Senha', meaning: 'Credencial exibida no perfil local; trate-a como dado sensível.' },
      { label: 'IP/Timezone', meaning: 'Contexto de rede e localização temporal associado à sessão.' },
      { label: 'Session ID', meaning: 'Identificador da sessão gerada pelo módulo.' },
    ],
    recommendedFlow: ['Leia o contexto do módulo.', 'Gere uma sessão.', 'Confira credenciais e contexto.', 'Use o botão de abertura do menu com cautela.'],
    whyDifferent: 'CPF, endereço, MAC e IMEI podem não aparecer porque a finalidade principal é sessão e contexto, não persona civil ou hardware completo.',
    limitations: 'Credenciais são sensíveis e não devem ser compartilhadas. A aplicação não garante autenticação ou permanência de uma sessão externa.',
  },
  gmail: {
    key: 'gmail', title: 'Gmail Master', family: 'Conta e recuperação',
    mission: 'Gerenciar um perfil de conta Google com credenciais, recuperação e contexto de sessão.',
    scope: 'Este menu enfatiza a conta e os dados de recuperação; não deve ser comparado campo a campo com um gerador de hardware.',
    fields: [
      { label: 'Gmail principal', meaning: 'Endereço principal da conta gerada ou selecionada.' },
      { label: 'Email/telefone de recuperação', meaning: 'Canais auxiliares associados ao perfil de recuperação.' },
      { label: 'Data de nascimento', meaning: 'Campo de persona exibido para o contexto da conta.' },
      { label: 'IP/Timezone', meaning: 'Contexto de rede e fuso horário atribuído ao perfil.' },
    ],
    recommendedFlow: ['Leia o escopo de conta.', 'Gere o perfil.', 'Revise os dados de recuperação.', 'Use a ação do menu somente após validar o que será exibido.'],
    whyDifferent: 'A interface exibe recuperação e conta porque esse é o objetivo do módulo; outros dados técnicos podem permanecer fora do cartão resumido.',
    limitations: 'Senhas, emails e telefones são dados sensíveis. O módulo local não substitui as verificações e políticas do provedor.',
  },
  temu: {
    key: 'temu', title: 'Temu Device Master', family: 'E-commerce & App Nativo',
    mission: 'Gerar perfil técnico e simular WebView nativa da Temu com bypass de preços de aplicativo e cupons.',
    scope: 'Módulo focado em e-commerce mobile, injetando fingerprint de app de compras e bypass anti-bot.',
    fields: [
      { label: 'Dispositivo', meaning: 'Modelo e hardware móvel simulado.' },
      { label: 'TemuBridge', meaning: 'Simulação de ponte nativa e versão de app Temu.' },
      { label: 'Cupons', meaning: 'Flags ativas para ativação de ofertas e descontos de novo usuário.' },
      { label: 'Fingerprint', meaning: 'Assinatura anti-detecção avançada.' },
    ],
    recommendedFlow: ['Gere o dispositivo.', 'Mantenha a simulação de app nativo ativada.', 'Inicie a injeção para o fluxo Temu.'],
    whyDifferent: 'Possui bypass especializado em e-commerce mobile e preços exclusivos de aplicativo.',
    limitations: 'Simulações locais auxiliam no bypass, mas dependem das políticas da plataforma.',
  },
  dark: {
    key: 'dark', title: 'Dark Master Hub', family: 'Privacy & Onion Proxy',
    mission: 'Menu mestre interativo para gerenciamento de túneis proxy, spoofing de headers e portais de navegação blindados.',
    scope: 'Hub centralizado contendo submenus para túneis onion, sanitização HTTP e acesso direto a sites de alta privacidade.',
    fields: [
      { label: 'Túneis Proxy', meaning: 'Seleção e ativação de nós de relay encriptados (Tor/Offshore).' },
      { label: 'Spoofing Headers', meaning: 'Ocultação de assinaturas de navegador e proteções anti-rastreamento.' },
      { label: 'Portais Blindados', meaning: 'Atalhos diretos e seguros para serviços de auditoria e busca onion.' },
      { label: 'DNS Leak Guard', meaning: 'Blindagem contra vazamentos de IP e WebRTC na sessão.' },
    ],
    recommendedFlow: ['Navegue pelas abas do menu mestre.', 'Ative o túnel proxy desejado.', 'Utilize os atalhos de sites e ferramentas blindadas.'],
    whyDifferent: 'Funciona como um hub interativo completo de privacidade, reunindo ferramentas de rede e portais em um único painel.',
    limitations: 'O anonimato e a segurança dependem da correta utilização dos túneis e boas práticas operacionais.',
  },
  ursa: {
    key: 'ursa', title: 'Ursa AI Core', family: 'Agent Automation',
    mission: 'Orquestração de agentes autônomos de alta performance e pipelines de automação intensiva.',
    scope: 'Ambiente de controle para múltiplos modelos, execução assíncrona e injeção de session tokens.',
    fields: [
      { label: 'Agent ID', meaning: 'Identificador único da instância do agente.' },
      { label: 'Orchestration', meaning: 'Parâmetros de execução paralela ou sequencial.' },
      { label: 'Memory Pool', meaning: 'Persistência de histórico e contexto de tarefas.' },
      { label: 'API Bridge', meaning: 'Conectividade segura com endpoints de IA.' },
    ],
    recommendedFlow: ['Defina o escopo do agente.', 'Configure o pool de memória.', 'Inicie a execução automatizada.'],
    whyDifferent: 'Projetado para tarefas de automação em larga escala com múltiplos modelos e sessões paralelas.',
    limitations: 'Requer recursos adequados e conformidade com os limites das APIs integradas.',
  },
  skynetchat: {
    key: 'skynetchat', title: 'SkynetChat Master', family: 'Dark AI Chat',
    mission: 'Gerar perfil técnico e injetar blindagem de sessão para o SkynetChat com spoofing de hardware.',
    scope: 'Módulo dedicado ao SkynetChat com camuflagem de navegador e anti-detecção.',
    fields: [
      { label: 'Dispositivo', meaning: 'Hardware e fingerprint simulados para a sessão.' },
      { label: 'Chat Bridge', meaning: 'Ponte de comunicação segura e WebSocket encriptado.' },
      { label: 'Anti-Bot', meaning: 'Proteção contra rastreamento de IP e fingerprint.' },
    ],
    recommendedFlow: ['Gere o dispositivo.', 'Ative a proteção anti-fraude.', 'Inicie a injeção segura para SkynetChat.'],
    whyDifferent: 'Focado em privacidade para plataformas de IA descentralizadas.',
    limitations: 'Depende da disponibilidade do serviço de destino.',
  },
  deephat: {
    key: 'deephat', title: 'DeepHat Security Master', family: 'Dark Security',
    mission: 'Gerenciamento de credenciais e túnel de segurança para o DeepHat.',
    scope: 'Módulo de auditoria e segurança avançada com isolamento de contexto.',
    fields: [
      { label: 'Security Node', meaning: 'Nó de relay e criptografia simétrica.' },
      { label: 'Auth Token', meaning: 'Chave de sessão injetada no ambiente.' },
      { label: 'Headers', meaning: 'Spoofing de headers HTTP.' },
    ],
    recommendedFlow: ['Gere o perfil de segurança.', 'Ative o isolamento.', 'Conecte ao DeepHat.'],
    whyDifferent: 'Voltado a pesquisas de segurança e análises avançadas.',
    limitations: 'Uso restrito a fins educacionais e de pesquisa.',
  },
  venice: {
    key: 'venice', title: 'Venice AI Master', family: 'Dark AI Uncensored',
    mission: 'Geração de fingerprint e injeção de sessão privada para Venice AI.',
    scope: 'Ambiente blindado para interação com modelos de IA sem censura.',
    fields: [
      { label: 'Hardware', meaning: 'Perfil de dispositivo camuflado.' },
      { label: 'Venice Bridge', meaning: 'Injeção de parâmetros de sessão e privacidade.' },
      { label: 'Anti-Detection', meaning: 'Blindagem de WebRTC e Canvas.' },
    ],
    recommendedFlow: ['Gere o perfil.', 'Valide os parâmetros.', 'Inicie a injeção Venice AI.'],
    whyDifferent: 'Garante máxima privacidade em chats de IA sem censura.',
    limitations: 'Sujeito aos termos e condições da plataforma Venice AI.',
  },
  simplelogin: {
    key: 'simplelogin', title: 'SimpleLogin Master', family: 'Alias & Email Security',
    mission: 'Gerenciamento de aliases de email anônimos e credenciais seguras.',
    scope: 'Gerador de aliases e blindagem de caixas de entrada.',
    fields: [
      { label: 'Alias Gerado', meaning: 'Endereço de email anônimo para cadastro.' },
      { label: 'Provedor', meaning: 'Domínio de alias integrado.' },
      { label: 'Sessão', meaning: 'Sincronização com o SimpleLogin.' },
    ],
    recommendedFlow: ['Gere o alias.', 'Copie a credencial.', 'Inicie o redirecionamento seguro.'],
    whyDifferent: 'Focado em proteção de email com aliases dinâmicos.',
    limitations: 'Gerenciamento local e de redirecionamento.',
  },
  nastia: {
    key: 'nastia', title: 'Nastia.ai Master', family: 'AI Companion',
    mission: 'Gerador de perfil e sessão para plataformas de companheiros de IA (Nastia.ai).',
    scope: 'Simulação de app e navegador móvel para interações com Nastia.ai.',
    fields: [
      { label: 'Dispositivo', meaning: 'Perfil de smartphone e WebView simulado.' },
      { label: 'Companion Bridge', meaning: 'Injeção de tokens de sessão e cookies.' },
      { label: 'Fingerprint', meaning: 'Assinatura anti-detecção.' },
    ],
    recommendedFlow: ['Gere o dispositivo.', 'Ative o simulador nativo.', 'Inicie a injeção Nastia.ai.'],
    whyDifferent: 'Otimizado para plataformas de interação com avatares de IA.',
    limitations: 'Simulação local de ambiente de cliente.',
  },
  uncensored: {
    key: 'uncensored', title: 'Uncensored Local Workspace', family: 'Dark / IA externa',
    mission: 'Preparar uma ficha técnica sintética e um checklist local antes de abrir o portal oficial Uncensored.',
    scope: 'O menu documenta compatibilidade local e mantém autenticação, conteúdo e controles de segurança no domínio oficial.',
    fields: [
      { label: 'Perfil técnico', meaning: 'Modelo, resolução e identificadores sintéticos exibidos somente no navegador local.' },
      { label: 'Checklist de privacidade', meaning: 'Pacote de referência local que não é executado nem enviado ao destino.' },
      { label: 'Acesso oficial', meaning: 'Link que abre https://uncensored.com/ em nova aba.' },
    ],
    recommendedFlow: ['Leia os limites do menu.', 'Gere o perfil local se precisar documentar um cenário de teste.', 'Abra o site oficial e use somente os fluxos autorizados.'],
    whyDifferent: 'O serviço externo controla conta, autenticação, políticas e mecanismos antiabuso; o projeto apenas organiza uma preparação local.',
    limitations: 'Não há bypass de CAPTCHA/anti-bot, manipulação de cookies ou tokens, nem promessa de aceitação pelo serviço.',
  },
  atomicmail: {
    key: 'atomicmail', title: 'Atomic Mail Local Workspace', family: 'Dark / Email privado',
    mission: 'Preparar uma ficha técnica sintética e um checklist local antes de abrir o portal oficial Atomic Mail.',
    scope: 'O menu organiza diagnóstico local sem tocar em caixa postal, credenciais, tokens, cookies ou controles do provedor.',
    fields: [
      { label: 'Perfil técnico', meaning: 'Dados sintéticos de dispositivo para documentação e testes locais.' },
      { label: 'Persona de teste', meaning: 'Identidade fictícia gerada localmente; não representa uma conta existente.' },
      { label: 'Acesso oficial', meaning: 'Link que abre https://atomicmail.io/ em nova aba.' },
    ],
    recommendedFlow: ['Leia o escopo.', 'Gere uma ficha local somente para testes controlados.', 'Abra o site oficial e siga os termos do provedor.'],
    whyDifferent: 'A criação e o uso de contas dependem exclusivamente da autenticação e das regras do serviço externo.',
    limitations: 'O projeto não cria contas, não intercepta emails e não contorna verificações ou controles de abuso.',
  },
  hackaigc: {
    key: 'hackaigc', title: 'HackAIGC Workspace', family: 'Van Gogh / Criação',
    mission: 'Organizar uma preparação local para o portal HackAIGC em português e abrir o endereço oficial.',
    scope: 'O perfil técnico é informativo e local; geração de conteúdo e autenticação permanecem no serviço oficial.',
    fields: [
      { label: 'Perfil local', meaning: 'Resumo sintético de hardware e navegador para inspeção.' },
      { label: 'Categoria', meaning: 'Entrada do catálogo de criação com IA.' },
      { label: 'Destino', meaning: 'https://www.hackaigc.com/pt.' },
    ],
    recommendedFlow: ['Revise o guia.', 'Prepare o perfil local se necessário.', 'Abra o HackAIGC oficial e opere de forma autorizada.'],
    whyDifferent: 'O catálogo não replica as ferramentas do site nem envia prompts; ele oferece uma entrada organizada e independente.',
    limitations: 'Não automatiza a plataforma, não altera limites de uso e não contorna autenticação ou moderação.',
  },
  leonardo: {
    key: 'leonardo', title: 'Leonardo.Ai Workspace', family: 'Van Gogh / Imagem e vídeo',
    mission: 'Organizar uma preparação local para Leonardo.Ai e abrir o endereço oficial em nova aba.',
    scope: 'O módulo é um painel de navegação e documentação; imagens, vídeos, API e contas permanecem no provedor.',
    fields: [
      { label: 'Perfil local', meaning: 'Dados sintéticos para revisar compatibilidade do navegador.' },
      { label: 'Destino', meaning: 'https://leonardo.ai.' },
      { label: 'Status', meaning: 'Indica se o diagnóstico local foi preparado, não se o site aceitou o perfil.' },
    ],
    recommendedFlow: ['Leia os limites.', 'Gere o diagnóstico local opcional.', 'Abra Leonardo.Ai e siga as políticas oficiais.'],
    whyDifferent: 'O módulo não controla modelos, créditos, prompts ou autenticação; apenas centraliza o acesso solicitado.',
    limitations: 'Não envia conteúdo ao site, não contorna controles e não garante disponibilidade de qualquer recurso externo.',
  },
  playground: {
    key: 'playground', title: 'Playground AI Workspace', family: 'Van Gogh / Design',
    mission: 'Organizar uma preparação local para Playground AI e abrir o endereço oficial.',
    scope: 'A ficha local serve para inspeção e documentação; criação, modelos e conta são operados somente pelo serviço externo.',
    fields: [
      { label: 'Perfil local', meaning: 'Resumo técnico sintético sem comunicação com o destino.' },
      { label: 'Destino', meaning: 'https://playgroundai.com.' },
      { label: 'Abertura', meaning: 'Link externo em nova aba com aviso de escopo.' },
    ],
    recommendedFlow: ['Confira o escopo.', 'Prepare o diagnóstico somente se necessário.', 'Continue no site oficial com autorização.'],
    whyDifferent: 'O menu evita duplicar ou automatizar as ferramentas de design do provedor e atua como um índice seguro.',
    limitations: 'Não automatiza geração, não manipula sessão e não interfere em limites, preços ou políticas.',
  },
  'hackaigc-lab': {
    key: 'hackaigc-lab', title: 'HackAIGC Lab Workspace', family: 'Van Gogh / Laboratório',
    mission: 'Oferecer uma segunda entrada independente para o destino HackAIGC, conforme solicitado, com diagnóstico local separado.',
    scope: 'Este submenu mantém estado e histórico locais próprios, embora a URL oficial seja a mesma do submenu HackAIGC.',
    fields: [
      { label: 'Entrada independente', meaning: 'A aba possui seu próprio estado de perfil e diagnóstico.' },
      { label: 'Destino', meaning: 'https://www.hackaigc.com/pt.' },
      { label: 'Histórico local', meaning: 'Registro sintético guardado pelo projeto para documentação.' },
    ],
    recommendedFlow: ['Leia as limitações.', 'Gere uma ficha independente se quiser comparar cenários locais.', 'Abra o destino oficial e respeite suas regras.'],
    whyDifferent: 'A duplicidade foi preservada como dois submenus independentes, sem duplicar a integração externa nem criar acesso privilegiado.',
    limitations: 'Não realiza injeções ou bypass; o destino e suas políticas continuam sendo os mesmos.',
  },
  pika: {
    key: 'pika', title: 'Pika Workspace', family: 'Van Gogh / Vídeo',
    mission: 'Organizar uma preparação local para Pika e abrir o endereço oficial para criação de vídeo.',
    scope: 'O painel documenta o ambiente local; prompts, modelos, agentes e conta são tratados exclusivamente no site oficial.',
    fields: [
      { label: 'Perfil local', meaning: 'Dados sintéticos de navegador e dispositivo para inspeção.' },
      { label: 'Destino', meaning: 'https://pika.art.' },
      { label: 'Checklist', meaning: 'Indicadores locais de preparação, sem execução remota.' },
    ],
    recommendedFlow: ['Leia o escopo.', 'Prepare o perfil local opcional.', 'Abra Pika e use os recursos de acordo com os termos oficiais.'],
    whyDifferent: 'O projeto não replica geração de vídeo nem acessa API; ele mantém o submenu como um atalho organizado.',
    limitations: 'Não automatiza prompts, não altera planos e não contorna login, moderação ou limites.',
  },
  runway: {
    key: 'runway', title: 'Runway Workspace', family: 'Van Gogh / Vídeo e IA',
    mission: 'Organizar uma preparação local para Runway e abrir o endereço oficial informado pelo usuário.',
    scope: 'O link preservado é https://runwayml.com; o domínio pode redirecionar para a página oficial atual do Runway.',
    fields: [
      { label: 'Perfil local', meaning: 'Resumo sintético para inspeção antes da navegação.' },
      { label: 'Destino informado', meaning: 'https://runwayml.com.' },
      { label: 'Destino resolvido', meaning: 'O domínio pode apresentar a página atual em https://runway.com/.' },
    ],
    recommendedFlow: ['Leia a observação sobre redirecionamento.', 'Prepare o diagnóstico local se necessário.', 'Continue no site oficial e siga seus controles de conta e uso.'],
    whyDifferent: 'O endereço informado foi preservado no catálogo e o navegador decide o redirecionamento oficial do domínio.',
    limitations: 'Não automatiza criação, não manipula sessões e não promete acesso a recursos, planos ou APIs do Runway.',
  },
  mercadolibre: {
    key: 'mercadolibre', title: 'Mercado Livre Device Master', family: 'Marketplace LATAM & Anti-Fraude ML',
    mission: 'Gerar perfil técnico e persona sintética para o fluxo do Mercado Livre, com simulação de app nativo e blindagem de Device ID e Tracking.',
    scope: 'Módulo focado em marketplace mobile, injetando fingerprint de app de compras (MLBridge) e proteção anti-bot do ecossistema ML.',
    fields: [
      { label: 'Dispositivo', meaning: 'Modelo e hardware móvel simulado.' },
      { label: 'ML Device ID', meaning: 'Identificador sintético persistente do ecossistema Mercado Livre.' },
      { label: 'ML Tracking', meaning: 'Token de rastreamento de sessão blindado para consistência entre perfis.' },
      { label: 'Persona', meaning: 'Dados sintéticos locais (nome, email, telefone, CPF, endereço) para fins de teste de cadastro.' },
    ],
    recommendedFlow: ['Gere o perfil técnico e a persona.', 'Mantenha a simulação de app nativo ativada.', 'Inicie a injeção para o fluxo Mercado Livre.'],
    whyDifferent: 'Possui bypass especializado em marketplace mobile LATAM com Device ID e Tracking próprios do ML.',
    limitations: 'Simulações locais auxiliam na consistência de perfil, mas dependem das políticas da plataforma.',
  },
  amazon: {
    key: 'amazon', title: 'Amazon Device Master', family: 'E-commerce Global & Anti-Fraud',
    mission: 'Gerar perfil técnico e persona sintética para o fluxo da Amazon, com blindagem de tokens de device (ubid-main, session-id) e anti-fraude.',
    scope: 'Módulo focado em e-commerce de alta proteção anti-fraude, com tokens persistentes e simulação de WebView de compras.',
    fields: [
      { label: 'Dispositivo', meaning: 'Modelo e hardware móvel simulado.' },
      { label: 'ubid Token', meaning: 'Token de device sintético no padrão ubid-main da Amazon.' },
      { label: 'Device Token', meaning: 'Token de sessão persistente injetado no ambiente local.' },
      { label: 'Persona', meaning: 'Dados sintéticos locais (nome, email, telefone, CPF, endereço) para fins de teste de cadastro.' },
    ],
    recommendedFlow: ['Gere o perfil técnico e a persona.', 'Mantenha a simulação de app nativo ativada.', 'Inicie a injeção para o fluxo Amazon.'],
    whyDifferent: 'A Amazon exige tokens de device persistentes e consistência timezone/locale, cobertos por este gerador específico.',
    limitations: 'Simulações locais auxiliam na consistência de perfil, mas dependem das políticas da plataforma.',
  },
  shopee: {
    key: 'shopee', title: 'Shopee Device Master', family: 'Marketplace SEA & Anti-Cheating',
    mission: 'Gerar perfil técnico e persona sintética para o fluxo da Shopee, com blindagem de Device ID e SPSID contra o sistema anti-cheating (SACS).',
    scope: 'Módulo focado em marketplace mobile SEA, com simulação de WebView de compras e proteção contra detecção de múltiplas contas.',
    fields: [
      { label: 'Dispositivo', meaning: 'Modelo e hardware móvel simulado.' },
      { label: 'SP Device ID', meaning: 'Identificador sintético persistente do ecossistema Shopee.' },
      { label: 'SPSID', meaning: 'Token de sessão no padrão SPSID blindado para consistência.' },
      { label: 'Persona', meaning: 'Dados sintéticos locais (nome, email, telefone, CPF, endereço) para fins de teste de cadastro.' },
    ],
    recommendedFlow: ['Gere o perfil técnico e a persona.', 'Mantenha a simulação de app nativo ativada.', 'Inicie a injeção para o fluxo Shopee.'],
    whyDifferent: 'Possui bypass especializado contra o anti-cheating da Shopee (SACS) com Device ID e SPSID próprios.',
    limitations: 'Simulações locais auxiliam na consistência de perfil, mas dependem das políticas da plataforma.',
  },
  'github-manager': {
    key: 'github-manager', title: 'GitHub Device Master', family: 'Plataforma Dev & Anti-Abuse GitHub',
    mission: 'Suite anti-detecção completa para o cadastro oficial do GitHub (github.com/signup), com shield anti-abuse, fingerprint blindado e injeção 16+.',
    scope: 'Módulo focado no sistema anti-abuse do GitHub, injetando device-id sintético, sessões Unicorn, WebRTC guard, detecção de WebDriver e comportamento humano realista antes de abrir o formulário de signup.',
    fields: [
      { label: 'Dispositivo', meaning: 'Device ID sintético, MAC, IMEI e fingerprint blindados.' },
      { label: 'Device ID GitHub', meaning: 'Identificador sintético persistente injetado no padrão _gh_og_device_id.' },
      { label: 'Sessões Unicorn', meaning: 'Tokens de sessão sintéticos (_gh_unicorn_session / _gh_user_session) para consistência.' },
      { label: 'Anti-Abuse Shield', meaning: 'Desativa webdriver/headless e bloqueia vazamento de IP via WebRTC.' },
      { label: 'Persona', meaning: 'Dados sintéticos locais (nome, email, telefone, CPF, endereço) para fins de teste de cadastro.' },
    ],
    recommendedFlow: ['Gere o perfil técnico e a persona.', 'Mantenha o shield anti-bot e o app nativo ativados.', 'Inicie a injeção — o cadastro do GitHub abre diretamente com a blindagem ativa.'],
    whyDifferent: 'Abre direto na URL oficial de cadastro (github.com/signup) e injeta device-id e telemetria sintéticos que o GitHub usa para detecção de abuso.',
    limitations: 'Simulações locais auxiliam na consistência de perfil, mas dependem das políticas da plataforma.',
  },
  'discord-site': {
    key: 'discord-site', title: 'Discord - Site Device Master', family: 'Plataforma de Chat & Anti-Moderação Discord',
    mission: 'Suite anti-detecção completa para o registro oficial do Discord (discord.com/register), com shield anti-bot, superprops sintéticas e injeção 16+.',
    scope: 'Módulo focado no sistema de moderação do Discord, injetando device ID sintético, superproperties de telemetria, WebRTC guard, detecção de WebDriver, app nativo simulado e comportamento humano realista antes de abrir o formulário de registro.',
    fields: [
      { label: 'Dispositivo', meaning: 'Device ID sintético, MAC, IMEI e fingerprint blindados.' },
      { label: 'Device ID Discord', meaning: 'Identificador sintético persistente injetado no padrão _discord_device_id.' },
      { label: 'Superprops', meaning: 'Telemetria sintética (os, browser, client_build_number) no padrão Discord.' },
      { label: 'Anti-Bot Shield', meaning: 'Desativa webdriver/headless e bloqueia vazamento de IP via WebRTC.' },
      { label: 'Persona', meaning: 'Dados sintéticos locais (nome, email, telefone, CPF, endereço) para fins de teste de registro.' },
    ],
    recommendedFlow: ['Gere o perfil técnico e a persona.', 'Mantenha o shield anti-bot e o app nativo ativados.', 'Inicie a injeção — o registro do Discord abre diretamente com a blindagem ativa.'],
    whyDifferent: 'Abre direto na URL oficial de registro (discord.com/register) e injeta superproperties e device ID sintéticos que o Discord usa para detecção de automação.',
    limitations: 'Simulações locais auxiliam na consistência de perfil, mas dependem das políticas da plataforma.',
  },
  'scooby-doo': {
    key: 'scooby-doo', title: 'Scooby-Doo Delivery Hub', family: 'Delivery & Anti-Fraud Suite',
    mission: 'Hub mestre para gerenciamento de contas em plataformas de delivery (iFood e Zé Delivery) com bypass de geolocalização e anti-fraude.',
    scope: 'Central de injeção especializada em apps de delivery, com simulação de WebView nativo, spoofing de coordenadas GPS, blindagem de IMEI/Android ID e comportamento humano realista.',
    fields: [
      { label: 'Geolocalização', meaning: 'Spoofing de coordenadas (Lat/Lng) em capitais brasileiras para bypass de raio de entrega.' },
      { label: 'Native Bridge', meaning: 'Simulação de objetos globais dos apps (iFoodBridge, ZeBridge).' },
      { label: 'Device Masking', meaning: 'Blindagem de identificadores de hardware para evitar banimento por device.' },
      { label: 'Persona', meaning: 'Dados sintéticos para teste de fluxo de pedido e cadastro.' },
    ],
    recommendedFlow: ['Escolha a plataforma de delivery no hub.', 'Gere o perfil técnico com geolocalização ativa.', 'Inicie a injeção para abrir o portal de delivery blindado.'],
    whyDifferent: 'Único módulo com foco total em bypass de geolocalização e anti-fraude específico para ecossistemas de delivery mobile.',
    limitations: 'A precisão da geolocalização simulada depende da aceitação do navegador/WebView de destino.',
  },
  shein: {
    key: 'shein', title: 'SHEIN Device Master', family: 'Fast Fashion & Anti-Bot SHEIN',
    mission: 'Suite anti-detecção completa para o fluxo da SHEIN (shein.com.br), com nova identidade MAC/IMEI, injeção de cookies de sessão, blindagem anti-bot e simulação de app nativo.',
    scope: 'Módulo focado em fast fashion mobile, injetando device fingerprint, cookies de sessão (device_id, sid, countryCode, currency), GPS spoofing em capitais brasileiras e comportamento humano realista antes de abrir o fluxo.',
    fields: [
      { label: 'Dispositivo', meaning: 'Modelo e hardware móvel simulado com MAC, IMEI e Android ID.' },
      { label: 'SHEIN Device ID', meaning: 'Identificador sintético persistente no padrão SDID do ecossistema SHEIN.' },
      { label: 'Sessão & Cookies', meaning: 'Cookies de sessão sintéticos (sid, session_id, countryCode, currency, _csrf) injetados no ambiente local.' },
      { label: 'GPS Spoofing', meaning: 'Coordenadas sintéticas em capitais brasileiras para consistência de geolocalização.' },
      { label: 'Persona', meaning: 'Dados sintéticos locais (nome, email, telefone, CPF, endereço) para fins de teste de cadastro.' },
    ],
    recommendedFlow: ['Gere o perfil técnico com a nova identidade MAC.', 'Mantenha a simulação de app nativo e o GPS ativos.', 'Inicie a injeção para abrir o fluxo SHEIN blindado.'],
    whyDifferent: 'Cobre o pacote completo do projeto para fast fashion: nova identidade de hardware, cookies de sessão, blindagem anti-bot 16+ e simulação de app nativo SHEIN.',
    limitations: 'Simulações locais auxiliam na consistência de perfil, mas dependem das políticas da plataforma.',
  },
  cider: {
    key: 'cider', title: 'Cider Device Master', family: 'Fast Fashion Global & Anti-Fraud Cider',
    mission: 'Suite anti-detecção completa para o fluxo da Cider (shopcider.com), com nova identidade MAC/IMEI, injeção de cookies de sessão, blindagem anti-fraude e simulação de app nativo.',
    scope: 'Módulo focado em fast fashion global, injetando device fingerprint, cookies de sessão (device_id, guest_id, sid), GPS spoofing e comportamento humano realista antes de abrir o fluxo.',
    fields: [
      { label: 'Dispositivo', meaning: 'Modelo e hardware móvel simulado com MAC, IMEI e Android ID.' },
      { label: 'Cider Device ID', meaning: 'Identificador sintético persistente no padrão CDID do ecossistema Cider.' },
      { label: 'Sessão & Cookies', meaning: 'Cookies de sessão sintéticos (device_id, guest_id, sid, countryCode, currency, _csrf) injetados no ambiente local.' },
      { label: 'GPS Spoofing', meaning: 'Coordenadas sintéticas em capitais brasileiras para consistência de geolocalização.' },
      { label: 'Persona', meaning: 'Dados sintéticos locais (nome, email, telefone, CPF, endereço) para fins de teste de cadastro.' },
    ],
    recommendedFlow: ['Gere o perfil técnico com a nova identidade MAC.', 'Mantenha a simulação de app nativo e o GPS ativos.', 'Inicie a injeção para abrir o fluxo Cider blindado.'],
    whyDifferent: 'Cobre o pacote completo do projeto para fast fashion global: nova identidade de hardware, cookies de sessão, blindagem anti-fraude e simulação de app nativo Cider.',
    limitations: 'Simulações locais auxiliam na consistência de perfil, mas dependem das políticas da plataforma.',
  },
  ugphone: {
    key: 'ugphone', title: 'UGPhone Device Master', family: 'Cloud Phone & Gaming Portal UGPhone',
    mission: 'Suite anti-detecção completa para o portal oficial da UGPhone (ugphone.com/toc-portal), com nova identidade MAC/IMEI, injeção de sessão e cookies, blindagem anti-bot e simulação de app nativo.',
    scope: 'Módulo focado no portal de login/criação da UGPhone (cloud phone), injetando device fingerprint, token de sessão, região de nó e comportamento humano realista antes de abrir o fluxo de cadastro.',
    fields: [
      { label: 'Dispositivo', meaning: 'Modelo e hardware móvel simulado com MAC, IMEI e Android ID.' },
      { label: 'UGPhone Device ID', meaning: 'Identificador sintético persistente no padrão UGD do portal UGPhone.' },
      { label: 'Sessão & Cookies', meaning: 'Cookies de sessão sintéticos (device_id, session_token, region, plan, _csrf) injetados no ambiente local.' },
      { label: 'Região & Plano', meaning: 'Nó de região sintético (Hong Kong, Taiwan, Japão, EUA...) e plano de cloud phone (UVIP, GVIP, KVIP, MVIP).' },
      { label: 'Persona', meaning: 'Dados sintéticos locais (nome, email, telefone, CPF, endereço) para fins de teste de cadastro.' },
    ],
    recommendedFlow: ['Gere o perfil técnico com a nova identidade MAC.', 'Mantenha a simulação de app nativo e a blindagem ativos.', 'Inicie a injeção — o portal de login/criação da UGPhone abre direto com a blindagem ativa.'],
    whyDifferent: 'Abre direto na URL oficial de login/criação (ugphone.com/toc-portal/#/login) e injeta device ID, sessão e cookies sintéticos com consistência de região e plano.',
    limitations: 'Simulações locais auxiliam na consistência de perfil, mas dependem das políticas da plataforma.',
  },
};
